version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/lambda/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/cdk/"
    schedule:
      interval: "weekly"
