version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/api"
      - "/astro"
      - "/cdk"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    groups:
      npm-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "swift"
    directory: "/lambda"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    groups:
      swift-v1-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      swift-v1-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "swift"
    directory: "/lambda-v2"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    groups:
      swift-v2-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      swift-v2-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
