name: Build Lambda on PRs

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'lambda/**'
      - 'lambda-v2/**'

env:
  SWIFT_VERSION: '6.2.1'

jobs:
  build-lambda:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7

      - name: Set up Swift
        uses: swift-actions/setup-swift@v3
        with:
          skip-verify-signature: true
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Test Swift Lambda
        working-directory: ./lambda
        run: swift test

      - name: Package Swift API Lambda
        working-directory: ./lambda
        run: DOCKER_DEFAULT_PLATFORM=linux/arm64 swift package --disable-sandbox --allow-network-connections docker archive --base-docker-image swift:amazonlinux2023 --disable-docker-image-update --products TorpinServiceLambda

      - name: Package Swift Event Handler Lambda
        working-directory: ./lambda
        run: DOCKER_DEFAULT_PLATFORM=linux/arm64 swift package --disable-sandbox --allow-network-connections docker archive --base-docker-image swift:amazonlinux2023 --disable-docker-image-update --products EventHandlerLambda

      - name: Test Swift Lambda v2
        working-directory: ./lambda-v2
        run: swift test

      - name: Package Swift Lambda v2
        working-directory: ./lambda-v2
        run: DOCKER_DEFAULT_PLATFORM=linux/arm64 swift package --disable-sandbox --allow-network-connections docker archive --base-docker-image swift:amazonlinux2023 --disable-docker-image-update --products EventHandlerV2Lambda
