name: Build on PRs

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package Swift Lambda
        working-directory: ./lambda
        run: swift package archive --disable-sandbox plugin

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install CDK Dependencies
        working-directory: ./cdk
        run: npm install

      - name: Install CDK Globally
        run: npm install -g aws-cdk

      - name: Synthesize CDK
        working-directory: ./cdk
        run: npx cdk synth

      - name: Install web Dependencies
        working-directory: ./astro
        run: npm install

      - name: Build web site
        working-directory: ./astro
        run: npm run build